<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <!-- emit a runtimeconfig.json so the native host can start the runtime -->
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
</Project>
