NAME: "OpenBSD 7.9"
NAMESPACE: obsd79
LIMIT: 331
BAE: EFAULT

CALLS


1 void exit (word)
2 word fork (void)
3 word read (word, ptr, word)
4 word write (word, ptr, word)
5 word open (ptr, word, word)
6 word close (word)
7 word getentropy (ptr, word)
8 word __tfork (ptr, word)
9 word link (ptr, ptr)
10 word unlink (ptr)
11 word wait4 (word, ptr, word, ptr)
12 word chdir (ptr)
13 word fchdir (word)
14 word mknod (ptr, word, word)
15 word chmod (ptr, word)
16 word chown (ptr, word, word)
17 word obreak (intptr)
18 word getdtablecount (void)
19 word getrusage (word, ptr)
20 word getpid (void)
21 word mount (ptr, ptr, word, ptr)
22 word unmount (ptr, word)
23 word setuid (word)
24 word getuid (void)
25 word geteuid (void)
26 word ptrace (word, word, intptr, word)
27 word recvmsg (word, ptr, word)
28 word sendmsg (word, ptr, word)
29 word recvfrom (word, ptr, word, word, ptr, ptr)
30 word accept (word, ptr, ptr)
31 word getpeername (word, ptr, ptr)
32 word getsockname (word, ptr, ptr)
33 word access (ptr, word)
34 word chflags (ptr, word)
35 word fchflags (word, word)
36 void sync (void)

38 word stat (ptr, ptr)
39 word getppid (void)
40 word lstat (ptr, ptr)
41 word dup (word)
42 word fstatat (word, ptr, ptr, word)
43 word getegid (void)

45 word ktrace (ptr, word, word, word)
46 word sigaction (word, ptr, ptr)
47 word getgid (void)
48 word sigprocmask (word, word)
49 intptr mmap (intptr, word, word, word, word, dword)
50 word setlogin (ptr)
51 word acct (ptr)
52 word sigpending (void)
53 word fstat (word, ptr)
54 word ioctl (word, intptr, intptr)
55 word reboot (word)
56 word revoke (ptr)
57 word symlink (ptr, ptr)
58 word readlink (ptr, ptr, word)
59 word execve (ptr, ptr, ptr)
60 word umask (word)
61 word chroot (ptr)
62 word getfsstat (ptr, word, word)
63 word statfs (ptr, ptr)
64 word fstatfs (word, ptr)
65 word fhstatfs (ptr, ptr)
66 word vfork (void)
67 word gettimeofday (ptr, ptr)
68 word settimeofday (ptr, ptr)
69 word setitimer (word, ptr, ptr)
70 word getitimer (word, ptr)
71 word select (word, ptr, ptr, ptr, ptr)
72 word kevent (word, ptr, word, ptr, word, ptr)
73 word munmap (ptr, word)
74 word mprotect (ptr, word, word)
75 word madvise (ptr, word, word)
76 word utimes (ptr, ptr)
77 word futimes (word, ptr)
78 intptr mquery (intptr, word, word, word, word, dword)
79 word getgroups (word, ptr)
80 word setgroups (word, ptr)
81 word getpgrp (void)
82 word setpgid (word, word)
83 word futex (ptr, word, word, ptr, ptr)
84 word utimensat (word, ptr, ptr, word)
85 word futimens (word, ptr)
86 word kbind (ptr, word, dword)
87 word clock_gettime (word, ptr)
88 word clock_settime (word, ptr)
89 word clock_getres (word, ptr)
90 word dup2 (word, word)
91 word nanosleep (ptr, ptr)
92 word fcntl (word, word, intptr)
93 word accept4 (word, ptr, ptr, word)
94 word __thrsleep (ptr, word, ptr, ptr, ptr)
95 word fsync (word)
96 word setpriority (word, word, word)
97 word socket (word, word, word)
98 word connect (word, ptr, word)
99 word getdents (word, ptr, word)
100 word getpriority (word, word)
101 word pipe2 (ptr, word)
102 word dup3 (word, word, word)
103 word sigreturn (ptr)
104 word bind (word, ptr, word)
105 word setsockopt (word, word, word, ptr, word)
106 word listen (word, word)
107 word chflagsat (word, ptr, word, word)
108 word pledge (ptr, ptr)
109 word ppoll (ptr, word, ptr, ptr)
110 word pselect (word, ptr, ptr, ptr, ptr, ptr)
111 word sigsuspend (word)
112 word sendsyslog (ptr, word, word)

114 word unveil (ptr, ptr)
115 word __realpath (ptr, ptr)
116 word recvmmsg (word, ptr, word, word, ptr)
117 word sendmmsg (word, ptr, word, word)
118 word getsockopt (word, word, word, ptr, ptr)
119 word thrkill (word, word, ptr)
120 word readv (word, ptr, word)
121 word writev (word, ptr, word)
122 word kill (word, word)
123 word fchown (word, word, word)
124 word fchmod (word, word)
125 word __pledge_open (ptr, word, word)
126 word setreuid (word, word)
127 word setregid (word, word)
128 word rename (ptr, ptr)

131 word flock (word, word)
132 word mkfifo (ptr, word)
133 word sendto (word, ptr, word, word, ptr, word)
134 word shutdown (word, word)
135 word socketpair (word, word, word, ptr)
136 word mkdir (ptr, word)
137 word rmdir (ptr)

140 word adjtime (ptr, ptr)
141 word getlogin_r (ptr, word)
142 word getthrname (word, ptr, word)
143 word setthrname (word, ptr)

147 word setsid (void)
148 word quotactl (ptr, word, word, ptr)

150 word ypconnect (word)

155 word nfssvc (word, ptr)

158 word pinsyscalls (ptr, word, ptr, word)
159 word mimmutable (ptr, word)
160 word waitid (word, word, ptr, word)
161 word getfh (ptr, ptr)

165 word sysarch (word, ptr)
166 dword lseek (word, dword, word)
167 word truncate (ptr, dword)
168 word ftruncate (word, dword)
169 word pread (word, ptr, word, dword)
170 word pwrite (word, ptr, word, dword)
171 word preadv (word, ptr, word, dword)
172 word pwritev (word, ptr, word, dword)

175 word profil (ptr, word, word, intptr, word, word)

181 word setgid (word)
182 word setegid (word)
183 word seteuid (word)

190 intptr pathconfat (word, ptr, word, word)
191 intptr pathconf (ptr, word)
192 intptr fpathconf (word, word)
193 word swapctl (word, ptr, word)
194 word getrlimit (word, ptr)
195 word setrlimit (word, ptr)

202 word sysctl (ptr, word, ptr, ptr, ptr, word)
203 word mlock (ptr, word)
204 word munlock (ptr, word)

207 word getpgid (word)

209 word utrace (ptr, ptr, word)

221 word semget (word, word, word)

225 word msgget (word, word)
226 word msgsnd (word, ptr, word, word)
227 word msgrcv (word, ptr, word, intptr, word)
228 intptr shmat (word, ptr, word)

230 word shmdt (ptr)

250 word minherit (ptr, word, word)

252 word poll (ptr, word, word)
253 word issetugid (void)
254 word lchown (ptr, word, word)
255 word getsid (word)
256 word msync (ptr, word, word)

263 word pipe (ptr)
264 word fhopen (ptr, word)

269 word kqueue (void)
270 word kqueue1 (word)
271 word mlockall (word)
272 word munlockall (void)

281 word getresuid (ptr, ptr, ptr)
282 word setresuid (word, word, word)
283 word getresgid (ptr, ptr, ptr)
284 word setresgid (word, word, word)

287 word closefrom (word)
288 word sigaltstack (ptr, ptr)
289 word shmget (word, word, word)
290 word semop (word, ptr, word)

294 word fhstat (ptr, ptr)
295 word __semctl (word, word, word, ptr)
296 word shmctl (word, word, ptr)
297 word msgctl (word, word, ptr)
298 word sched_yield (void)
299 word getthrid (void)

301 word __thrwakeup (ptr, word)
302 void __threxit (ptr)
303 word __thrsigdivert (word, ptr, ptr)
304 word __getcwd (ptr, word)
305 word adjfreq (ptr, ptr)

310 word setrtable (word)
311 word getrtable (void)

313 word faccessat (word, ptr, word, word)
314 word fchmodat (word, ptr, word, word)
315 word fchownat (word, ptr, word, word, word)

317 word linkat (word, ptr, word, ptr, word)
318 word mkdirat (word, ptr, word)
319 word mkfifoat (word, ptr, word)
320 word mknodat (word, ptr, word, word)
321 word openat (word, ptr, word, word)
322 word readlinkat (word, ptr, ptr, word)
323 word renameat (word, ptr, word, ptr)
324 word symlinkat (ptr, word, ptr)
325 word unlinkat (word, ptr, word)

329 void __set_tcb (ptr)
330 intptr __get_tcb (void)
